### ISSUE TITLE
Slide Printer Sample Format

### ISSUE THREAD

**Issue by dspencer-kc** [openaplis/ap-pm#5]
@SidHarder 

I've found a contact with Leica who will help with implementing an interface between OPENLIS and the PermaS Slide printers, which the slide printers will essentially be watching a shared folder.  I now have all the pieces of software to implement this, Nicelabel PowerForms and NiceLabel Automation.  The leica technical contact asked if I could provide him a sample flat file that will be dropped in the folder, and he will go ahead and create a configuration template to print it.

Do you have a sample of the slide flat file that we will be using?  If so, could you upload it, and I will have him start that process.

**Comment by SidHarder** [comment]
[20180508140737085.pdf](https://github.com/openaplis/ap-pm/files/1985433/20180508140737085.pdf)

This pdf is what our slides currently look like.

**Comment by SidHarder** [comment]
This is an example of a file we have used in the past:

18-12043.S|1A1|MOUSE|YPI Blgs, Mt|^2205HSLD18-12043.1A1

But we can create what ever makes sense.  I would ask them to send an example of what they are used to seeing and then I will generate one.
